apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: etcds.etcd.zrq.org.cn
spec:
  group: etcd.zrq.org.cn
  names:
    kind: Etcd
    listKind: EtcdList
    plural: etcds
    singular: etcd
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Etcd is the Schema for the etcds API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EtcdSpec defines the desired state of Etcd
          properties:
            cluster:
              type: boolean
            image:
              type: string
            initClusterType:
              type: string
            insecure:
              type: boolean
            replicas:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              format: int32
              type: integer
            resources:
              description: ResourceRequirements describes the compute resource requirements.
              properties:
                limits:
                  additionalProperties:
                    anyOf:
                    - type: integer
                    - type: string
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  description: 'Limits describes the maximum amount of compute resources
                    allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                  type: object
                requests:
                  additionalProperties:
                    anyOf:
                    - type: integer
                    - type: string
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  description: 'Requests describes the minimum amount of compute resources
                    required. If Requests is omitted for a container, it defaults
                    to Limits if that is explicitly specified, otherwise to an implementation-defined
                    value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                  type: object
              type: object
            storage:
              format: int32
              type: integer
          required:
          - cluster
          - image
          - initClusterType
          - insecure
          - replicas
          - resources
          - storage
          type: object
        status:
          description: EtcdStatus defines the observed state of Etcd
          properties:
            collisionCount:
              description: collisionCount is the count of hash collisions for the
                StatefulSet. The StatefulSet controller uses this field as a collision
                avoidance mechanism when it needs to create the name for the newest
                ControllerRevision.
              format: int32
              type: integer
            conditions:
              description: Represents the latest available observations of a statefulset's
                current state.
              items:
                description: StatefulSetCondition describes the state of a statefulset
                  at a certain point.
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of statefulset condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            currentReplicas:
              description: currentReplicas is the number of Pods created by the StatefulSet
                controller from the StatefulSet version indicated by currentRevision.
              format: int32
              type: integer
            currentRevision:
              description: currentRevision, if not empty, indicates the version of
                the StatefulSet used to generate Pods in the sequence [0,currentReplicas).
              type: string
            observedGeneration:
              description: observedGeneration is the most recent generation observed
                for this StatefulSet. It corresponds to the StatefulSet's generation,
                which is updated on mutation by the API Server.
              format: int64
              type: integer
            readyReplicas:
              description: readyReplicas is the number of Pods created by the StatefulSet
                controller that have a Ready Condition.
              format: int32
              type: integer
            replicas:
              description: replicas is the number of Pods created by the StatefulSet
                controller.
              format: int32
              type: integer
            updateRevision:
              description: updateRevision, if not empty, indicates the version of
                the StatefulSet used to generate Pods in the sequence [replicas-updatedReplicas,replicas)
              type: string
            updatedReplicas:
              description: updatedReplicas is the number of Pods created by the StatefulSet
                controller from the StatefulSet version indicated by updateRevision.
              format: int32
              type: integer
          required:
          - replicas
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
